package com.todociber.hesidohackeado.bd;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table HACKEADO.
 */
public class Hackeado {

    private Long id;
    private String correo;
    private String title;
    private String author;
    private String is_vrf;
    private String date_created;
    private String date_leaked;
    private String emails_count;
    private String details;
    private String source_id;
    private String source_url;
    private String source_lines;
    private String source_size;
    private String source_network;
    private String source_provider;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Hackeado() {
    }

    public Hackeado(Long id) {
        this.id = id;
    }

    public Hackeado(Long id, String correo, String title, String author, String is_vrf, String date_created, String date_leaked, String emails_count, String details, String source_id, String source_url, String source_lines, String source_size, String source_network, String source_provider) {
        this.id = id;
        this.correo = correo;
        this.title = title;
        this.author = author;
        this.is_vrf = is_vrf;
        this.date_created = date_created;
        this.date_leaked = date_leaked;
        this.emails_count = emails_count;
        this.details = details;
        this.source_id = source_id;
        this.source_url = source_url;
        this.source_lines = source_lines;
        this.source_size = source_size;
        this.source_network = source_network;
        this.source_provider = source_provider;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getIs_vrf() {
        return is_vrf;
    }

    public void setIs_vrf(String is_vrf) {
        this.is_vrf = is_vrf;
    }

    public String getDate_created() {
        return date_created;
    }

    public void setDate_created(String date_created) {
        this.date_created = date_created;
    }

    public String getDate_leaked() {
        return date_leaked;
    }

    public void setDate_leaked(String date_leaked) {
        this.date_leaked = date_leaked;
    }

    public String getEmails_count() {
        return emails_count;
    }

    public void setEmails_count(String emails_count) {
        this.emails_count = emails_count;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public String getSource_id() {
        return source_id;
    }

    public void setSource_id(String source_id) {
        this.source_id = source_id;
    }

    public String getSource_url() {
        return source_url;
    }

    public void setSource_url(String source_url) {
        this.source_url = source_url;
    }

    public String getSource_lines() {
        return source_lines;
    }

    public void setSource_lines(String source_lines) {
        this.source_lines = source_lines;
    }

    public String getSource_size() {
        return source_size;
    }

    public void setSource_size(String source_size) {
        this.source_size = source_size;
    }

    public String getSource_network() {
        return source_network;
    }

    public void setSource_network(String source_network) {
        this.source_network = source_network;
    }

    public String getSource_provider() {
        return source_provider;
    }

    public void setSource_provider(String source_provider) {
        this.source_provider = source_provider;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
