package com.todociber.hesidohackeado;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CORREOS.
 */
public class Correos {

    private Long id;
    private String email;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Correos() {
    }

    public Correos(Long id) {
        this.id = id;
    }

    public Correos(Long id, String email) {
        this.id = id;
        this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
