package com.todociber.hesidohackeado;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.todociber.hesidohackeado.Correos;
import com.todociber.hesidohackeado.Hackeado;

import com.todociber.hesidohackeado.CorreosDao;
import com.todociber.hesidohackeado.HackeadoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig correosDaoConfig;
    private final DaoConfig hackeadoDaoConfig;

    private final CorreosDao correosDao;
    private final HackeadoDao hackeadoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        correosDaoConfig = daoConfigMap.get(CorreosDao.class).clone();
        correosDaoConfig.initIdentityScope(type);

        hackeadoDaoConfig = daoConfigMap.get(HackeadoDao.class).clone();
        hackeadoDaoConfig.initIdentityScope(type);

        correosDao = new CorreosDao(correosDaoConfig, this);
        hackeadoDao = new HackeadoDao(hackeadoDaoConfig, this);

        registerDao(Correos.class, correosDao);
        registerDao(Hackeado.class, hackeadoDao);
    }
    
    public void clear() {
        correosDaoConfig.getIdentityScope().clear();
        hackeadoDaoConfig.getIdentityScope().clear();
    }

    public CorreosDao getCorreosDao() {
        return correosDao;
    }

    public HackeadoDao getHackeadoDao() {
        return hackeadoDao;
    }

}
